# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = 1024
    vb.cpus = 1
  
    vb.linked_clone = true
    vb.check_guest_additions = false

    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.customize ["modifyvm", :id, "--groups", "/marr"]
  end


  # Infrastructure:
  # Local apt mirror to cache packages to save time and bandwidth.
  config.vm.define "infra-mirror" do |mirror|
    mirror.vm.network "private_network", ip: "192.168.57.11", name: "vboxnet1"

    mirror.vm.provider "virtualbox" do |v|
      v.name = "infra-mirror"
      v.customize ["modifyvm", :id, "--groups", "/marr/infra"]
    end

    mirror.vm.provision "shell", path: "vagrant/provision-mirror.sh"

  end


  # Development environment
  (1..2).each do |n|
    config.vm.define "dev-#{n}" do |dev|
      hostname = "dev-app-0#{n}"
      dev.vm.network "private_network", ip: "192.168.57.#{100 + n}", name: "vboxnet1"

      dev.vm.provider "virtualbox" do |v|
        v.name = hostname
        v.customize ["modifyvm", :id, "--groups", "/marr/dev"]
      end

      dev.vm.provision "shell", path: "vagrant/provision-common.sh", env: {
        "MIRROR" => "http://192.168.57.11:3128",
        "HOSTNAME" => hostname,
        "PUBLIC_KEY" => File.new("vagrant/id_dev.pub").read,
      }
    end
  end

  # Production environment
  (1..2).each do |n|
    config.vm.define "prod-#{n}", autostart: false do |prod|
      hostname = "prod-app-0#{n}"
      prod.vm.network "private_network", ip: "192.168.57.#{120 + n}", name: "vboxnet1"

      prod.vm.provider "virtualbox" do |v|
        v.name = hostname
        v.customize ["modifyvm", :id, "--groups", "/marr/prod"]
      end

      prod.vm.provision "shell", path: "vagrant/provision-common.sh", env: {
        "MIRROR" => "http://192.168.57.11:3128",
        "HOSTNAME" => hostname,
        "PUBLIC_KEY" => File.new("vagrant/id_prod.pub").read,
      }
    end
  end

end
